name: "[searcher] build container image"

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GCP_REGISTRY: asia-northeast1-docker.pkg.dev
  GCP_IMAGE_NAME: iwanhae/cloudrun/kuberian

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Configure Docker CLI"
        run: "gcloud auth configure-docker ${{ env.GCP_REGISTRY }}"

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata for GHCR
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=semver,pattern={{version}}

      - name: Extract Docker metadata for GCR
        id: meta-gcr
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.GCP_REGISTRY }}/${{ env.GCP_IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=semver,pattern={{version}}

      - name: Build and Push cache
        id: build-and-push-cache
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./searcher
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: builder
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push to GCR
        id: build-and-push-gcr
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./searcher
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-gcr.outputs.tags }}
          labels: ${{ steps.meta-gcr.outputs.labels }}
          cache-from: type=gha
